### PR TITLE
New: Add Spanish accounting plan

### PR DESCRIPTION
**Pull request by simnandez**

### CODE REVIEW

**Comment by simnandez** [comment]
Ok, thanks for you note. I have to change a few lines...

**Comment by simnandez** [comment]
Are you sure about account_parent must be contain the rowid of parent account instead the acount number of parent? in the french and belgium plan (htdocs/install/mysql/data/llx_accounting.sql) it refers to the account number of parent

**Comment by aspangaro** [comment]
Hi Simnandez,

Yes, I'm sure.

I have pushed a PR on 3.6 before freeze (https://github.com/Dolibarr/dolibarr/commit/25f2fec4739c30b89ec3b0c670893da227baafd1) but with your question, I see the branch develop is not up to date.

In fact, I will be pushed a new PR on branch develop too.

Thanks

**Comment by simnandez** [comment]
Ok, but there's something I do not understand.

1 - In your changes, ex:

INSERT INTO llx_accountingaccount (rowid, fk_pcg_version, pcg_type, pcg_subtype, account_number, account_parent, label, active) VALUES (  1,'PCG99-ABREGE','CAPIT', 'CAPITAL', '101', '1401', 'Capital', '1');

The 1401 should be the rowid of account parent, but rowid 1401 not exist!

2 - in the htdocs/custom/accountingex/admin/account.php we should showing the name of account parent instead the number of rowid of account parent... what do you think?

**Comment by simnandez** [comment]
Sorry about the 1... 1401 exists!!!

**Comment by aspangaro** [comment]
Hi Simnandez

For question 2, the module is not perfect for the moment. You're right, is more user friendly if the name of the account parent is showing instead of the rowid of account parent.

I will work in few days on the module and we have a lot of bugs to correct on 3.5 and develop branch.

**Pull request closed without merging**
